using FluentValidation;

namespace Schoolera.Application.SchoolPortal.Commands.UnpublishSchoolChildAgeEligibilityRule;

public sealed class UnpublishSchoolChildAgeEligibilityRuleCommandValidator
    : AbstractValidator<UnpublishSchoolChildAgeEligibilityRuleCommand>;
