using FluentValidation;

namespace Schoolera.Application.SchoolPortal.Commands.PublishSchoolChildAgeEligibilityRule;

public sealed class PublishSchoolChildAgeEligibilityRuleCommandValidator
    : AbstractValidator<PublishSchoolChildAgeEligibilityRuleCommand>;
