using FluentValidation;

namespace Schoolera.Application.SchoolPortal.Commands.GenerateInterviewAssessmentSlotRecurrence;

public sealed class GenerateInterviewAssessmentSlotRecurrenceCommandValidator
    : AbstractValidator<GenerateInterviewAssessmentSlotRecurrenceCommand>;
